### PR TITLE
Fixed smart indent when pressing Enter inside {}

### PR DESCRIPTION
**Pull request by atsepkov**
There do seem to be test cases for this, however, this functionality did not work for me in vim 7.3. I attached a fix.

### CODE REVIEW

**Comment by faceleg** [comment]
Can this be merged? @kana?

**Comment by rgrinberg** [comment]
@kana ?

**Comment by faceleg** [comment]
@kanaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by rgrinberg** [comment]
Senpaaaiiiiiiiiiiiiiii

**Comment by Shougo** [comment]
@atsepkov You should remove tags file from this PR.

**Comment by atsepkov** [comment]
Hey guys, sorry for being slow to respond, have a few other projects I've been working on. By tags, do you mean `docs/tags`? I think that was there with the original version I forked from, but I have no problem removing it. Also, just wanted to mention, I've made a number of changes in my own fork since the merge request, mainly revolving around better handling of block spacing and indentation and automatic semi-colon/comma addition/removal. That's something the community may or may not want (although judging by comments from other members it sounds like they do).

**Comment by Shougo** [comment]
> I think that was there with the original version I forked from, but I have no problem removing it. 

Oh, OK.

@kana ping

**Comment by faceleg** [comment]
@kana

**Comment by suy** [comment]
I'm not sure what it should be done with this pull request, but I think it should be closed and start over. The commits that are sent to this pull request do a lot more than what it was originally intended, have some errors/noise, and in the end just fork the plugin while renaming it.

**Comment by atsepkov** [comment]
Agreed, I made this pull request a long time ago. Since then I've tweaked a lot of the library to make it more suitable for my own needs. At this time to pull request is no longer relevant, and I have long forgotten about it.

**Pull request closed without merging**
